name: Build Size Report

on:
  pull_request_target:
    branches:
      - master

jobs:
  report-build-size-diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: preactjs/compressed-size-action@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          run: "echo ${{ secrets.GITHUB_TOKEN }}"
          pattern: "./packages/core/dist/**/*.{js,css}"
          compression: 'none'
